const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const storage={get(k,f='[]'){try{return localStorage.getItem(k)||f}catch{return f}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
const state={all:[],shown:[],direct:[],providers:{},query:'',favorites:new Set(JSON.parse(storage.get('oshiru-v5-favs'))),compare:new Map(),broken:new Set(),loaded:new Set(),searchSeq:0};
const retailSources=['メルカリ','Yahoo!フリマ','Yahoo!オークション','Yahoo!ショッピング','楽天市場'];
const sourceOrder=[...retailSources,'X'];
const liveStatuses=new Set(['販売中','販売中候補','入札受付中','交換募集中','譲渡募集中','交換・譲渡候補']);
const fmt=n=>n==null?'不明':'¥'+Number(n).toLocaleString('ja-JP');
const total=i=>(i.price==null||i.shipping==null)?null:Number(i.price)+Number(i.shipping||0)+Number(i.fee||0);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dt=s=>{if(!s)return'不明';const d=new Date(s);return Number.isNaN(+d)?'不明':d.toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})};
const originLabel=o=>({'verified-snapshot':'検証済み実出品','web-index-snapshot':'Web確認済み','public-page-live':'現在取得','openai-web-search':'Web検索','official-api':'公式API'}[o]||'取得元確認');
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
async function json(url,opts){const r=await fetch(url,opts);const text=await r.text();if(!r.ok)throw new Error(text||`${r.status}`);return JSON.parse(text)}
function debounce(fn,ms=300){let id;return(...a)=>{clearTimeout(id);id=setTimeout(()=>fn(...a),ms)}}
function sourceClass(s){if(s==='メルカリ')return'mercari';if(s==='Yahoo!フリマ')return'yflea';if(s==='Yahoo!オークション')return'yauc';return'shop'}
function sourceMode(s){return(s==='Yahoo!ショッピング'||s==='楽天市場')?'公式API':'サイト内検索'}
function sourceSearchUrl(source,q){const e=encodeURIComponent(q||'推し活 グッズ');if(source==='メルカリ')return`https://jp.mercari.com/search?keyword=${e}`;if(source==='Yahoo!フリマ')return`https://paypayfleamarket.yahoo.co.jp/search/${e}`;if(source==='Yahoo!オークション')return`https://auctions.yahoo.co.jp/search/search/${e}/0/`;if(source==='Yahoo!ショッピング')return`https://shopping.yahoo.co.jp/search?p=${e}`;if(source==='楽天市場')return`https://search.rakuten.co.jp/search/mall/${e}/`;if(source==='X')return`https://x.com/search?f=live&q=${e}`;return'#'}
function directLinks(q){return retailSources.map(source=>({source,url:sourceSearchUrl(source,q)}))}
function remoteImage(i){return /^https?:\/\//i.test(i.image||'')}
function officialImageProvider(i){if(i?.origin!=='official-api')return'';if(i.source==='Yahoo!ショッピング')return'yahoo';if(i.source==='楽天市場')return'rakuten';return''}
function imageSrc(i){const raw=i.image||'';if(!raw)return'';const provider=officialImageProvider(i);return provider?`/api/image-proxy?source=${provider}&url=${encodeURIComponent(raw)}`:raw}
function itemLive(i){return liveStatuses.has(i.status)}
async function runSearch(){
  const q=$('#q').value.trim(); const seq=++state.searchSeq; state.query=q; state.broken.clear(); state.loaded.clear();state.direct=directLinks(q);
  $('#queryBadge').textContent=q?`「${q}」`:'すべて'; $('#resultMeta').textContent='個別出品を検索しています…'; $('#productGrid').innerHTML=loadingCards(); $('#emptyState').classList.add('hidden'); $('#providerNotice').classList.add('hidden');
  const btn=$('#searchBtn');btn.classList.add('loading');btn.textContent='検索中…';
  try{
    const data=await json(`/api/search?q=${encodeURIComponent(q)}`);if(seq!==state.searchSeq)return;
    state.all=data.items||[];state.direct=directLinks(q);state.providers=data.providers||{};
    hydrateFilters();applyFilters();renderProviderNotice(true);refreshLive(q,seq);
  }catch(e){
    if(seq!==state.searchSeq)return;state.all=[];state.direct=directLinks(q);hydrateFilters();renderEmpty('検索サーバーに接続できませんでした','販売サイトへの直接検索リンクをご利用ください。');console.error(e);
  }finally{if(seq===state.searchSeq){btn.classList.remove('loading');btn.textContent='横断検索'}}
}
async function refreshLive(q,seq){
  if(!q)return;
  try{
    const live=await json(`/api/live-search?q=${encodeURIComponent(q)}`);if(seq!==state.searchSeq)return;
    const seen=new Set(),merged=[];for(const i of [...(live.items||[]),...state.all]){const k=(i.url||`${i.source}|${i.title}|${i.price}`).replace(/[?#].*$/,'');if(seen.has(k))continue;seen.add(k);merged.push(i)}
    state.all=merged;state.providers={...state.providers,...(live.providers||{})};hydrateFilters();applyFilters();renderProviderNotice(false);
  }catch(e){if(seq===state.searchSeq){state.providers.liveError=String(e.message||e);renderProviderNotice(false)}}
}
function loadingCards(){return Array.from({length:8},()=>`<div class="product-card"><div class="visual skeleton"></div><div class="card-body"><div class="skeleton line"></div><div class="skeleton line short"></div><div class="skeleton price-sk"></div></div></div>`).join('')}
function hydrateFilters(){
  const current=new Set($$('.source-check:checked').map(x=>x.value));
  const checked=current.size?current:new Set(retailSources);
  $('#sourceFilters').innerHTML=retailSources.map(s=>`<label><input class="source-check" type="checkbox" value="${esc(s)}" ${checked.has(s)?'checked':''}><span class="source-dot ${sourceClass(s)}"></span><span>${esc(s)}</span><span class="source-mode ${sourceMode(s)==='公式API'?'api':''}">${sourceMode(s)}</span></label>`).join('');
  $$('.source-check').forEach(x=>x.onchange=applyFilters);
  const currentCollab=$('#collabFilter').value;const cs=[...new Set(state.all.map(x=>x.collab).filter(Boolean))].sort();$('#collabFilter').innerHTML='<option value="">すべて</option>'+cs.map(c=>`<option ${c===currentCollab?'selected':''}>${esc(c)}</option>`).join('');
}
function applyFilters(){
  const sources=new Set($$('.source-check:checked').map(x=>x.value));const type=$('#typeFilter').value;const collab=$('#collabFilter').value;const max=Number($('#maxPrice').value);const imageOnly=$('#imageOnly').checked;const includeEnded=$('#includeEnded').checked;const liveOnly=$('#liveOnly').checked;
  let arr=sources.size?state.all.filter(i=>{if(!sources.has(i.source))return false;if(type&&i.type!==type)return false;if(collab&&i.collab!==collab)return false;if(!includeEnded&&i.status==='終了')return false;if(liveOnly&&!itemLive(i))return false;const t=total(i);if(t!=null&&t>max)return false;if(imageOnly&&(!i.image||i.imageVerified!==true||state.broken.has(String(i.id))))return false;return true}):[];
  const sort=$('#sort').value;if(sort==='price')arr.sort((a,b)=>(total(a)??a.price??Infinity)-(total(b)??b.price??Infinity));else if(sort==='source')arr.sort((a,b)=>sourceOrder.indexOf(a.source)-sourceOrder.indexOf(b.source));else if(sort==='new')arr.sort((a,b)=>new Date(b.verifiedAt||0)-new Date(a.verifiedAt||0));else arr.sort((a,b)=>(b._score||0)-(a._score||0)||(a.price??Infinity)-(b.price??Infinity));state.shown=arr;render();
}
function render(){
  $('#favCount').textContent=state.favorites.size;const arr=state.shown;$('#resultMeta').textContent=`${arr.length}件表示 / 取得候補 ${state.all.length}件`;renderStats(arr);if(!arr.length){$('#productGrid').innerHTML='';renderEmpty();return}else $('#emptyState').classList.add('hidden');$('#productGrid').innerHTML=arr.map(card).join('');bindCards();
}
function renderStats(arr){const costs=arr.map(total).filter(Number.isFinite);const prices=arr.map(x=>x.price).filter(Number.isFinite);const sources=new Set(arr.map(x=>x.source));const withImage=arr.filter(x=>x.image&&x.imageVerified===true&&!state.broken.has(String(x.id))).length;const min=costs.length?Math.min(...costs):(prices.length?Math.min(...prices):null);$('#stats').innerHTML=`<div class="stat"><span>表示件数</span><b>${arr.length}件</b></div><div class="stat"><span>最安候補</span><b>${fmt(min)}</b></div><div class="stat"><span>商品取得元</span><b>${sources.size}サイト</b></div><div class="stat"><span>画像あり</span><b>${withImage}件</b></div>`}
function card(i){
  const t=total(i),shipping=i.shipping===0?'送料無料':i.shipping==null?'送料不明':`送料 ${fmt(i.shipping)}`;
  const ended=i.status==='終了',src=imageSrc(i),id=String(i.id),favorite=state.favorites.has(id),compared=state.compare.has(id);
  return `<article class="product-card" data-card-id="${esc(id)}"><div class="visual">${src?`<img class="market-img" src="${esc(src)}" alt="${esc(i.title)}" loading="lazy" decoding="async" width="320" height="320" data-id="${esc(id)}" data-remote="0" data-proxy="">`:`<div class="image-fallback">画像を取得できません<br><small>商品ページでは確認できます</small></div>`}<span class="source-pill"><span class="source-dot ${sourceClass(i.source)}"></span>${esc(i.source)}</span><span class="gallery-price">${fmt(i.price)}</span><button type="button" class="heart ${favorite?'on':''}" data-fav="${esc(id)}" aria-label="${favorite?'お気に入りから外す':'お気に入りに追加'}" aria-pressed="${favorite}">${favorite?'♥':'♡'}</button><button type="button" class="gallery-compare ${compared?'is-selected':''}" data-compare="${esc(id)}" aria-label="${compared?'比較から外す':'比較に追加'}" aria-pressed="${compared}">${compared?'✓':'＋'}</button></div><div class="card-body"><div class="tag-row"><span class="tag ${ended?'ended':'live'}">${esc(i.status||'要確認')}</span><span class="tag">${esc(i.type||'その他')}</span>${i.collab?`<span class="tag collab">${esc(i.collab)}</span>`:''}<span class="tag snap">${esc(originLabel(i.origin))}</span></div><div class="product-title">${esc(i.title)}</div><div class="meta-line">${esc([i.series,i.character,i.shop].filter(Boolean).join(' / '))}</div><div class="price-block"><div class="main-price">${fmt(i.price)}</div><div class="ship">${shipping}<br>${t!=null?`実質 ${fmt(t)}`:'総額は要確認'}</div></div><div class="cost-row"><span>商品価格</span><b>${fmt(i.price)}</b><span>送料</span><b>${fmt(i.shipping)}</b><span>状態</span><b>${esc(i.condition||'要確認')}</b></div><div class="verified"><span>${esc(originLabel(i.origin))}</span><span>確認 ${esc(dt(i.verifiedAt))}</span></div><div class="card-actions"><a href="${esc(i.url)}" target="_blank" rel="noopener noreferrer">この出品を見る ↗</a></div></div></article>`
}
function bindCards(){
  $$('.market-img').forEach(img=>{img.addEventListener('load',()=>state.loaded.add(String(img.dataset.id)),{once:true});img.addEventListener('error',()=>{const id=String(img.dataset.id);state.broken.add(id);const card=img.closest('.product-card');if($('#imageOnly').checked){card?.classList.add('image-broken');setTimeout(()=>applyFilters(),0)}else img.outerHTML='<div class="image-fallback">商品画像を読み込めません<br><small>商品ページでは確認できます</small></div>'},{once:false})});
  $$('[data-fav]').forEach(b=>b.onclick=()=>{const id=String(b.dataset.fav);state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);storage.set('oshiru-v5-favs',JSON.stringify([...state.favorites]));render();toast(state.favorites.has(id)?'お気に入りに追加しました':'お気に入りから外しました')});
  $$('[data-compare]').forEach(b=>b.onclick=()=>{const id=String(b.dataset.compare),item=state.all.find(x=>String(x.id)===id);if(state.compare.has(id))state.compare.delete(id);else{if(state.compare.size>=4)state.compare.delete(state.compare.keys().next().value);state.compare.set(id,item)}updateCompare();render()});
}
function renderEmpty(title='条件に合う商品がありません',body='絞り込み条件を見直すか、各販売サイトを同じ検索語で直接確認してください。'){const box=$('#emptyState');box.classList.remove('hidden');box.innerHTML=`<h3>${esc(title)}</h3><p>${esc(body)}</p><div class="direct-links">${state.direct.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.source)}で同じ語を検索 ↗</a>`).join('')}</div>`}
function renderProviderNotice(loading=false){const p=state.providers||{};const publicP=p.public;const pills=[];if(loading)pills.push('<span class="provider-pill">リアルタイム取得中…</span>');if(publicP){for(const [name,r] of Object.entries(publicP.sources||{})){const label={mercari:'メルカリ',yahooFlea:'Yahoo!フリマ',yahooAuction:'Yahoo!オークション'}[name]||name;pills.push(`<span class="provider-pill ${r.ok?'ok':'bad'}">${label}: ${r.ok?`${r.count||0}件`:'取得制限'}</span>`)}}for(const [key,label] of [['openai','Web検索'],['yahooShopping','Yahoo!ショッピング'],['rakuten','楽天市場'],['x','X']]){if(p[key])pills.push(`<span class="provider-pill ${p[key].ok?'ok':'bad'}">${label}: ${p[key].count||0}件</span>`)}if(p.liveError)pills.push('<span class="provider-pill bad">ライブ取得エラー</span>');const show=loading||publicP||p.openai||p.yahooShopping||p.rakuten||p.x||p.liveError;if(!show){$('#providerNotice').classList.add('hidden');return}$('#providerNotice').innerHTML=`<b>${loading?'検索結果は先に表示しました。追加の商品を取得中です。':'リアルタイム取得状況'}</b><div>Yahoo!ショッピング・楽天市場は公式APIで取得します。その他の販売サイトは、同じ検索語のサイト内検索も常に利用できます。</div><div class="provider-row">${pills.join('')}</div>`;$('#providerNotice').classList.remove('hidden')}
function updateCompare(){const n=state.compare.size;$('#compareCount').textContent=n;$('#compareTray').classList.toggle('hidden',n===0)}
function openCompare(){const a=[...state.compare.values()];if(!a.length)return;$('#modalContent').innerHTML=`<h2>商品の比較</h2><p class="lead">商品価格だけでなく、送料と状態も合わせて比較します。</p><table class="compare-table"><tr><th>項目</th>${a.map(i=>`<th>${esc(i.source)}</th>`).join('')}</tr>${[['商品',i=>esc(i.title)],['価格',i=>fmt(i.price)],['送料',i=>fmt(i.shipping)],['実質額',i=>fmt(total(i))],['状態',i=>esc(i.condition||'要確認')],['販売状況',i=>esc(i.status||'要確認')],['確認',i=>esc(dt(i.verifiedAt))],['販売元',i=>`<a target="_blank" rel="noopener" href="${esc(i.url)}">個別出品 ↗</a>`]].map(([h,f])=>`<tr><th>${h}</th>${a.map(i=>`<td>${f(i)}</td>`).join('')}</tr>`).join('')}</table>`;openModal()}
async function openSettings(){let s={};try{s=await json('/api/status')}catch{}const rows=[['検証済み実出品',true,`${s.snapshot||0}件`],['AniList候補API',Boolean(s.anilist),'自動'],['Jikan候補API',Boolean(s.jikan),'自動'],['画像AI検索',Boolean(s.vision),s.vision?'接続済み':'APIキー未設定'],['Yahoo!ショッピング',Boolean(s.yahooShopping),s.yahooShopping?'接続済み':'APIキー未設定'],['楽天市場',Boolean(s.rakuten),s.rakuten?'接続済み':'APIキー未設定'],['X検索',Boolean(s.x),s.x?'接続済み':'APIキー未設定']];$('#modalContent').innerHTML=`<h2>データ接続状況</h2><p class="lead">秘密鍵はブラウザに埋め込まず、サーバー側の環境変数から読み込みます。</p><div class="settings-grid">${rows.map(([n,on,v])=>`<div class="setting-row"><span>${n}</span><b class="${on?'status-on':'status-off'}">${esc(v)}</b></div>`).join('')}</div>`;openModal()}
function openModal(){$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function imageSearch(){$('#modalContent').innerHTML=`<h2>画像・スクショから探す</h2><p class="lead">画像から作品名・キャラクター名・グッズ種別を抽出し、その検索語で横断検索します。</p><div class="image-search-zone"><b>画像を選択</b><br><input id="imgInput" type="file" accept="image/*"><div id="imgPreview"></div></div>`;openModal();setTimeout(()=>{$('#imgInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=async()=>{const data=reader.result;$('#imgPreview').innerHTML=`<img src="${data}" alt="アップロード画像"><div class="vision-result">画像解析中…</div>`;try{const r=await json('/api/vision-search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({imageData:data})});const q=r.query||'';$('#imgPreview .vision-result').innerHTML=`候補: <b>${esc(q||'判定できませんでした')}</b><br>信頼度: ${esc(r.confidence??'不明')}%${q?`<br><button id="visionApply">この候補で検索</button>`:''}`;if(q)$('#visionApply').onclick=()=>{$('#q').value=q;closeModal();runSearch()}}catch{$('#imgPreview .vision-result').innerHTML='画像は読み込めました。AI画像検索を使うにはサーバー側に OPENAI_API_KEY を設定してください。'}};reader.readAsDataURL(f)}} ,0)}
let suggestController=null,suggestIndex=-1;
function setSuggestActive(index){const rows=$$('#suggestBox [data-suggest]');if(!rows.length){suggestIndex=-1;return}suggestIndex=Math.max(-1,Math.min(index,rows.length-1));rows.forEach((row,i)=>{const active=i===suggestIndex;row.setAttribute('aria-selected',active?'true':'false');row.style.background=active?'#f1f5f9':''});if(suggestIndex>=0)rows[suggestIndex].scrollIntoView({block:'nearest'})}
function chooseSuggest(row){if(!row)return false;const value=row.dataset.suggest||'';if(!value)return false;$('#q').value=value;$('#suggestBox').classList.add('hidden');suggestIndex=-1;runSearch();return true}
const suggest=debounce(async()=>{const q=$('#q').value.trim(),box=$('#suggestBox');suggestIndex=-1;if(q.length<2){suggestController?.abort();box.classList.add('hidden');return}suggestController?.abort();const controller=new AbortController();suggestController=controller;try{const d=await json(`/api/suggest?q=${encodeURIComponent(q)}`,{signal:controller.signal});if(controller!==suggestController)return;const a=(d.items||[]).slice(0,8);if(!a.length){box.classList.add('hidden');return}box.setAttribute('role','listbox');box.setAttribute('aria-label','予測検索');box.innerHTML=`<div class="history-toolbar"><b>予測検索</b><span style="font-size:11px;color:#64748b;font-weight:700">人気・新着・一致度</span></div>`+a.map((x,i)=>`<div class="suggest-item" role="option" tabindex="-1" aria-selected="false" data-suggest-index="${i}" data-suggest="${esc(x.name)}">${x.image?`<img src="${esc(x.image)}" referrerpolicy="no-referrer" alt="">`:''}<div><b>${esc(x.name)}</b><span>${esc(x.label||(x.kind==='character'?'キャラクター':x.kind==='anime'?'作品':'検索候補'))}${x.detail?` ・ ${esc(x.detail)}`:''}</span></div></div>`).join('');box.classList.remove('hidden');$$('#suggestBox [data-suggest]').forEach(x=>x.onclick=()=>chooseSuggest(x))}catch(e){if(e?.name!=='AbortError'&&controller===suggestController)box.classList.add('hidden')}},500);
function watchRender(){const a=JSON.parse(storage.get('oshiru-v5-watch'));$('#watchList').innerHTML=a.slice(0,4).map((x,i)=>`<div class="watch-item"><span>${esc(x.q||'すべて')}</span><button data-watch-del="${i}">×</button></div>`).join('');$$('[data-watch-del]').forEach(b=>b.onclick=()=>{const a=JSON.parse(storage.get('oshiru-v5-watch'));a.splice(Number(b.dataset.watchDel),1);storage.set('oshiru-v5-watch',JSON.stringify(a));watchRender()})}
$('#searchBtn').onclick=()=>{$('#suggestBox').classList.add('hidden');suggestIndex=-1;runSearch()};$('#q').addEventListener('keydown',e=>{const box=$('#suggestBox'),rows=$$('#suggestBox [data-suggest]');if(!box.classList.contains('hidden')&&rows.length&&(e.key==='ArrowDown'||e.key==='ArrowUp')){e.preventDefault();setSuggestActive(e.key==='ArrowDown'?(suggestIndex+1)%rows.length:(suggestIndex<=0?rows.length-1:suggestIndex-1));return}if(e.key==='Escape'&&!box.classList.contains('hidden')){e.preventDefault();box.classList.add('hidden');suggestIndex=-1;return}if(e.key==='Enter'){e.preventDefault();if(suggestIndex>=0&&chooseSuggest(rows[suggestIndex]))return;box.classList.add('hidden');suggestIndex=-1;runSearch()}});$('#q').addEventListener('input',suggest);$('#clearQ').onclick=()=>{$('#q').value='';suggestController?.abort();suggestIndex=-1;$('#q').focus()};$$('.query-chip').forEach(b=>b.onclick=()=>{$('#q').value=b.dataset.query;runSearch()});['#typeFilter','#collabFilter','#liveOnly','#imageOnly','#includeEnded','#sort'].forEach(s=>$(s).onchange=applyFilters);$('#maxPrice').oninput=e=>{$('#maxPriceLabel').textContent=`${fmt(e.target.value)}以下`;applyFilters()};$('#resetBtn').onclick=()=>{$('#typeFilter').value='';$('#collabFilter').value='';$('#maxPrice').value=15000;$('#maxPriceLabel').textContent='¥15,000以下';$('#liveOnly').checked=true;$('#imageOnly').checked=false;$('#includeEnded').checked=false;$$('.source-check').forEach(x=>x.checked=true);applyFilters()};$('#saveWatchBtn').onclick=()=>{let a=JSON.parse(storage.get('oshiru-v5-watch'));a.unshift({q:state.query||$('#q').value.trim(),at:Date.now()});a=a.slice(0,8);storage.set('oshiru-v5-watch',JSON.stringify(a));watchRender();toast('検索条件を保存しました')};$('#favoritesBtn').onclick=()=>toast(`お気に入り ${state.favorites.size}件`);$('#clearCompare').onclick=()=>{state.compare.clear();updateCompare();render()};$('#openCompare').onclick=openCompare;$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#openSettings').onclick=openSettings;$('#imageSearchBtn').onclick=imageSearch;$('#mobileFilterBtn').onclick=()=>$('.filter-panel').classList.toggle('mobile-open');window.addEventListener('click',e=>{if(!e.target.closest('.search-panel')){$('#suggestBox').classList.add('hidden');suggestIndex=-1}});hydrateFilters();watchRender();runSearch();
