import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { DEFAULT_SITE as ROBOTS_SITE, renderRobots } from '../api/robots.js';
import { DEFAULT_SITE as SITEMAP_SITE, SITEMAP_ENTRIES, renderSitemap } from '../api/sitemap.js';
import seoHandler,{ SEO_PAGES, renderSeoPage } from '../api/seo-v2.js';

const ROOT=new URL('../',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,ROOT),'utf8');

function invokeSeo(section,slug){
  return new Promise((resolve,reject)=>{
    const headers={};
    const res={
      statusCode:200,
      setHeader(name,value){headers[String(name).toLowerCase()]=value},
      status(code){this.statusCode=code;return this},
      send(body){resolve({status:this.statusCode,headers,body:String(body)});return this}
    };
    Promise.resolve(seoHandler({query:{section,slug}},res)).catch(reject);
  });
}

test('production robots is generated by the environment-aware route and advertises the sitemap',()=>{
  assert.equal(fs.existsSync(new URL('robots.txt',ROOT)),false,'static robots.txt would shadow the Vercel function');
  assert.equal(ROBOTS_SITE,'https://oshiruoshi.vercel.app');
  assert.equal(SITEMAP_SITE,ROBOTS_SITE,'robots and sitemap must share one canonical origin');
  const production=renderRobots({indexable:true,base:'https://oshiruoshi.vercel.app'});
  assert.match(production,/^User-agent: \*$/m);
  assert.match(production,/^Allow: \/$/m);
  assert.match(production,/^Disallow: \/api\/$/m);
  assert.match(production,/^Disallow: \/\*\?q=$/m);
  assert.match(production,/^Sitemap: https:\/\/oshiruoshi\.vercel\.app\/sitemap\.xml$/m);
  assert.equal(renderRobots({indexable:false,base:'https://preview.example'}),'User-agent: *\nDisallow: /\n');
  const config=JSON.parse(read('vercel.json'));
  assert.ok(config.rewrites.some(rule=>rule.source==='/robots.txt'&&rule.destination==='/api/robots'));
});

test('sitemap has one canonical URL per public page with truthful last-modified dates',()=>{
  const xml=renderSitemap('https://oshiruoshi.vercel.app');
  const locations=[...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map(match=>match[1]);
  assert.equal(locations.length,SITEMAP_ENTRIES.length);
  assert.equal(new Set(locations).size,locations.length);
  assert.ok(locations.length>=20);
  assert.ok(locations.every(url=>url.startsWith('https://oshiruoshi.vercel.app/')));
  assert.ok(SITEMAP_ENTRIES.every(entry=>/^2026-\d{2}-\d{2}$/.test(entry.lastmod)));
  for(const {path} of SITEMAP_ENTRIES){
    if(/^\/(guide|compare|discover|character)\//.test(path))assert.ok(SEO_PAGES[path.slice(1)],path);
  }
});

test('SEO landing pages have unique metadata, useful page-specific copy and server-rendered structured data',()=>{
  const titles=new Set(),descriptions=new Set(),headings=new Set();
  for(const [key,page] of Object.entries(SEO_PAGES)){
    assert.ok(page.title&&!titles.has(page.title),`duplicate title: ${page.title}`);titles.add(page.title);
    assert.ok(page.description&&!descriptions.has(page.description),`duplicate description: ${page.description}`);descriptions.add(page.description);
    assert.ok(page.h1&&!headings.has(page.h1),`duplicate h1: ${page.h1}`);headings.add(page.h1);
    const html=renderSeoPage(page,key,null);
    assert.match(html,new RegExp(`<link rel="canonical" href="https://oshiruoshi\\.vercel\\.app${page.path.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}">`));
    assert.match(html,/meta name="oshiru-seo-version" content="2026-09-05\.18"/);
    assert.match(html,/type="application\/ld\+json" data-oshiru-structured/);
    assert.match(html,/このテーマで結果を絞る確認ポイント/);
    const json=html.match(/<script type="application\/ld\+json" data-oshiru-structured>(.*?)<\/script>/)?.[1];
    assert.doesNotThrow(()=>JSON.parse(json),key);
  }
});

test('crawler-facing SEO handler does not wait for live marketplace APIs',async()=>{
  const source=read('api/seo-v2.js');
  assert.doesNotMatch(source,/import\s*\{[^}]*liveSearch/);
  assert.doesNotMatch(source,/timeout\(liveSearch/);
  const started=performance.now();
  const response=await invokeSeo('character','gojo-satoru');
  assert.equal(response.status,200);
  assert.match(response.headers['x-robots-tag'],/index, follow/);
  assert.equal(response.headers['x-oshiru-seo-version'],'2026-09-05.18');
  assert.match(response.body,/五条悟グッズ/);
  assert.ok(performance.now()-started<2500,'SEO handler should not incur a multi-second external provider wait');
});

test('homepage exposes stable canonical metadata and server-rendered WebSite data',()=>{
  const home=read('index.html');
  assert.match(home,/meta name="last-modified" content="2026-09-05"/);
  assert.match(home,/type="application\/ld\+json" data-oshiru-structured/);
  assert.match(home,/"alternateName":"OSHIRU 推し活グッズ検索"/);
  assert.match(home,/property="og:title" content="OSHIRU \| 推し活グッズを横断検索・価格比較"/);
});
